### PR TITLE
Pull in updates to Notebook 2

### PR DESCRIPTION
**Pull request by jruzekow**

### CODE REVIEW

**Comment by samgdotson** [comment]
Thanks for the pull request @jruzekow. It's missing some important information. Generally, when creating a pull request one should provide the following: 

1. What change is being made
2. Why the change is being made (typically a pull request is made in response to an issue. Such as issue #2). 

Please edit the pull request or reply below with the information. Thanks!

**Comment by jruzekow** [comment]
1. Updating Notebook 2 to ignore warnings about doing assignments with a copy of the data. Data was copied into a new dataframe. 
2. Update removes red warnings to avoid confusion for notebook users.

**Comment by samgdotson** [comment]
> 1. Updating Notebook 2 to ignore warnings about doing assignments with a copy of the data. Data was copied into a new dataframe.

> 2. Update removes red warnings to avoid confusion for notebook users.

What are "red warnings?" Why would they be removed?

**Comment by jruzekow** [comment]
Aiming to ignore the following warning: 
<ipython-input-17-1ec8ebd71d3f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

**Pull request closed without merging**
